spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
#参数中url的值为百度，那就转发到百度，参数为qq，转发到qq
        - id: query_route2
          uri: https://www.qq.com
          predicates:
            - Query=url,qq